// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: proyecto_competencia

#ifndef _PROYECTO_COMPETENCIA_UI_H
#define _PROYECTO_COMPETENCIA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

void movengranaje1_Animation(lv_obj_t * TargetObject, int delay);
void movengranaje2_Animation(lv_obj_t * TargetObject, int delay);
void caja1_Animation(lv_obj_t * TargetObject, int delay);
void movengranaje3_Animation(lv_obj_t * TargetObject, int delay);
void movengranaje4_Animation(lv_obj_t * TargetObject, int delay);
void caja2_Animation(lv_obj_t * TargetObject, int delay);
void intermitentex_Animation(lv_obj_t * TargetObject, int delay);
void moveraguja_Animation(lv_obj_t * TargetObject, int delay);
void mostrar_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Image5;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
void ui_event_Panel6(lv_event_t * e);
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_imagesquare1;
extern lv_obj_t * ui_imagetriangle1;
extern lv_obj_t * ui_imagecircle1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Panel21;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Button5;
void ui_event_Panel22(lv_event_t * e);
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel23;
extern lv_obj_t * ui_Panel24;
extern lv_obj_t * ui_Panel25;
extern lv_obj_t * ui_Panel26;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Panel27;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel28;
extern lv_obj_t * ui_Panel29;
extern lv_obj_t * ui_Label11;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel30;
extern lv_obj_t * ui_Panel31;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel32;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel33;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
void ui_event_Image16(lv_event_t * e);
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Panel34;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Panel35;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Panel18;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Label17;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Panel37;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Panel38;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Image20;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Panel40;
extern lv_obj_t * ui_Panel39;
extern lv_obj_t * ui_Label18;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Panel41;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_imagesquare;
extern lv_obj_t * ui_imagetrangle;
extern lv_obj_t * ui_imagecircle;
// CUSTOM VARIABLES

// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Panel43;
extern lv_obj_t * ui_Image24;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Image26;
extern lv_obj_t * ui_Panel44;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Slider3;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_cambiobrazo;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label21;
// CUSTOM VARIABLES

// SCREEN: ui_Screen8
void ui_Screen8_screen_init(void);
void ui_event_Screen8(lv_event_t * e);
extern lv_obj_t * ui_Screen8;
extern lv_obj_t * ui_Panel45;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Image25;
extern lv_obj_t * ui_Panel42;
extern lv_obj_t * ui_Image27;
extern lv_obj_t * ui_Image28;
extern lv_obj_t * ui_Panel46;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Image30;
extern lv_obj_t * ui_Panel47;
extern lv_obj_t * ui_Panel48;
extern lv_obj_t * ui_Slider4;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_cambiobrazo2;
void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Label29;
// CUSTOM VARIABLES

// SCREEN: ui_Screen9
void ui_Screen9_screen_init(void);
extern lv_obj_t * ui_Screen9;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label28;
void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Image31;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_imagen1_png);    // assets/imagen1.png
LV_IMG_DECLARE(ui_img_engrane_png);    // assets/engrane.png
LV_IMG_DECLARE(ui_img_brazo_robot_png);    // assets/brazo_robot.png
LV_IMG_DECLARE(ui_img_engra_png);    // assets/engra.png
LV_IMG_DECLARE(ui_img_square_png);    // assets/square.png
LV_IMG_DECLARE(ui_img_triangle_png);    // assets/triangle.png
LV_IMG_DECLARE(ui_img_circle_png);    // assets/circle.png
LV_IMG_DECLARE(ui_img_bombillo_encendido_png);    // assets/bombillo_encendido.png
LV_IMG_DECLARE(ui_img_camara_png);    // assets/camara.png
LV_IMG_DECLARE(ui_img_banda_transportadora_png);    // assets/banda_transportadora.png
LV_IMG_DECLARE(ui_img_102514673);    // assets/flecha_atras_r (1).png
LV_IMG_DECLARE(ui_img_bombillo_apagado_png);    // assets/bombillo_apagado.png
LV_IMG_DECLARE(ui_img_velocimetro_without_png);    // assets/velocimetro_without.png
LV_IMG_DECLARE(ui_img_aguja_png);    // assets/aguja.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
