// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: proyecto_competencia

#ifndef _UI_COMP_PANEL1_H
#define _UI_COMP_PANEL1_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Panel1
#define UI_COMP_PANEL1_PANEL1 0
#define UI_COMP_PANEL1_LABEL2 1
#define UI_COMP_PANEL1_BUTTON3 2
#define _UI_COMP_PANEL1_NUM 3
lv_obj_t * ui_Panel1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
