// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: proyecto_competencia

#include "ui.h"

// COMPONENT Panel1

lv_obj_t * ui_Panel1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Panel1;
    cui_Panel1 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Panel1, 202);
    lv_obj_set_height(cui_Panel1, 214);
    lv_obj_set_x(cui_Panel1, 65);
    lv_obj_set_y(cui_Panel1, 115);
    lv_obj_set_align(cui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label2;
    cui_Label2 = lv_label_create(cui_Panel1);
    lv_obj_set_width(cui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label2, -1);
    lv_obj_set_y(cui_Label2, -66);
    lv_obj_set_align(cui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label2, "Boton");
    lv_obj_set_style_text_color(cui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Button3;
    cui_Button3 = lv_btn_create(cui_Panel1);
    lv_obj_set_width(cui_Button3, 130);
    lv_obj_set_height(cui_Button3, 50);
    lv_obj_set_x(cui_Button3, 2);
    lv_obj_set_y(cui_Button3, 63);
    lv_obj_set_align(cui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PANEL1_NUM);
    children[UI_COMP_PANEL1_PANEL1] = cui_Panel1;
    children[UI_COMP_PANEL1_LABEL2] = cui_Label2;
    children[UI_COMP_PANEL1_BUTTON3] = cui_Button3;
    lv_obj_add_event_cb(cui_Panel1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Panel1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Panel1_create_hook(cui_Panel1);
    return cui_Panel1;
}

