// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: proyecto_competencia

#include "ui.h"

// Flags used to indicate when data should be sent via UART
volatile bool send_arm  = false;   // Flag to send arm speed/value
volatile bool send_band = false;   // Flag to send conveyor belt speed/value

// Variables that store slider values
volatile int arm_value  = 0;       // Arm speed/value (0–100)
volatile int band_value = 0;       // Conveyor belt speed/value (0–100)

// Timers used to hide figures after a delay
static lv_timer_t * timer_ocultar_screen2 = NULL; // Timer for screen 2 figures
static lv_timer_t * timer_ocultar_screen6 = NULL; // Timer for screen 6 figures
static lv_timer_t * img_timer = NULL;              // Image animation timer
static lv_obj_t * img_actual = NULL;               // Currently displayed image

// External function used to send commands via UART
extern void sendUARTCommand(int cmd);

// Event callback to start the system
void iniciarsistema(lv_event_t * e)
{
	sendUARTCommand(1);  // Send command to start the system
}

// Event callback to stop the system
void prarsistema(lv_event_t * e)
{
	sendUARTCommand(0);  // Send command to stop the system
}

// Event callback to turn LED on
void turnonled(lv_event_t * e)
{
	sendUARTCommand(2);  // Send LED ON command
}

// Event callback to turn LED off
void turnoffled(lv_event_t * e)
{
	sendUARTCommand(3);  // Send LED OFF command
}

// Event callback for sending arm value when button is released
void enviarbrazo(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_RELEASED)
    {
        send_arm = true;  // Set flag to send arm value
    }
}

// Event callback for sending conveyor belt value when button is released
void enviarbanda(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_RELEASED)
    {
        send_band = true; // Set flag to send belt value
    }
}

// Displays a detected figure on screen 2 depending on classification value
void mostrar_figura_screen2(uint16_t valor)
{
    // Hide all figures first
    _ui_opacity_set(ui_imagesquare1, 0);
    _ui_opacity_set(ui_imagecircle1, 0);
    _ui_opacity_set(ui_imagetriangle1, 0);

    // Show the detected figure
    if(valor == 100) {
        _ui_opacity_set(ui_imagesquare1, 255); // Square detected
    }
    else if(valor == 200) {
        _ui_opacity_set(ui_imagecircle1, 255); // Circle detected
    }
    else if(valor == 300) {
        _ui_opacity_set(ui_imagetriangle1, 255); // Triangle detected
    }
    else {
        return; // Invalid value
    }

    // Restart timer if it already exists
    if(timer_ocultar_screen2) {
        lv_timer_del(timer_ocultar_screen2);
        timer_ocultar_screen2 = NULL;
    }

    // Create timer to hide figures after 2.5 seconds
    timer_ocultar_screen2 =
        lv_timer_create(ocultar_figuras_cb_screen2, 2500, NULL);
}

// Timer callback to hide figures on screen 2
void ocultar_figuras_cb_screen2(lv_timer_t * timer)
{
    _ui_opacity_set(ui_imagesquare1, 0);
    _ui_opacity_set(ui_imagecircle1, 0);
    _ui_opacity_set(ui_imagetriangle1, 0);

    timer_ocultar_screen2 = NULL;
    lv_timer_del(timer); // Delete timer
}

// Displays a detected figure on screen 6 depending on classification value
void mostrar_figura_screen6(uint16_t valor)
{
    // Hide all figures first
    _ui_opacity_set(ui_imagesquare, 0);
    _ui_opacity_set(ui_imagecircle, 0);
    _ui_opacity_set(ui_imagetrangle, 0);

    // Show the detected figure
    if(valor == 100) {
        _ui_opacity_set(ui_imagesquare, 255); // Square detected
    }
    else if(valor == 200) {
        _ui_opacity_set(ui_imagecircle, 255); // Circle detected
    }
    else if(valor == 300) {
        _ui_opacity_set(ui_imagetrangle, 255); // Triangle detected
    }
    else {
        return; // Invalid value
    }

    // Restart timer if it already exists
    if(timer_ocultar_screen6) {
        lv_timer_del(timer_ocultar_screen6);
        timer_ocultar_screen6 = NULL;
    }

    // Create timer to hide figures after 2.5 seconds
    timer_ocultar_screen6 =
        lv_timer_create(ocultar_figuras_cb_screen6, 2500, NULL);
}

// Timer callback to hide figures on screen 6
void ocultar_figuras_cb_screen6(lv_timer_t * timer)
{
    _ui_opacity_set(ui_imagesquare, 0);
    _ui_opacity_set(ui_imagecircle, 0);
    _ui_opacity_set(ui_imagetrangle, 0);

    timer_ocultar_screen6 = NULL;
    lv_timer_del(timer); // Delete timer
}

// Event callback for conveyor belt speed slider
void ui_event_Slider4(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED)
    {
        lv_obj_t * slider = lv_event_get_target(e);
        band_value = lv_slider_get_value(slider); // Read slider value

        // Update label with new value
        lv_label_set_text_fmt(ui_cambiobrazo2, "%d", band_value);
    }
}


// Event callback for robotic arm speed slider
void ui_event_Slider3(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_VALUE_CHANGED)
    {
        lv_obj_t * slider = lv_event_get_target(e);
        arm_value = lv_slider_get_value(slider); // Read arm value

        // Update label with arm value
        lv_label_set_text_fmt(ui_cambiobrazo, "%d", arm_value);
    }
}
