// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: proyecto_competencia

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void iniciarsistema(lv_event_t * e);
void prarsistema(lv_event_t * e);
void turnonled(lv_event_t * e);
void turnoffled(lv_event_t * e);
void enviarbrazo(lv_event_t * e);
void enviarbanda(lv_event_t * e);
void mostrar_figura_screen2(uint16_t valor);
void mostrar_figura_screen6(uint16_t valor);
void ocultar_figuras_cb_screen2(lv_timer_t * timer);
void ocultar_figuras_cb_screen6(lv_timer_t * timer);
void ui_event_Slider4(lv_event_t * e);
void ui_event_Slider3(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
