// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: proyecto_competencia

#include "ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6, lv_color_hex(0x000413), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -187);
    lv_obj_set_y(ui_Label20, -194);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "ESP32 Camera AI");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label20, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label20, lv_color_hex(0x012A91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label20, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label20, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel40 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_Panel40, 340);
    lv_obj_set_height(ui_Panel40, 347);
    lv_obj_set_x(ui_Panel40, -185);
    lv_obj_set_y(ui_Panel40, 30);
    lv_obj_set_align(ui_Panel40, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel40, lv_color_hex(0x004FB6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel40, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel40, lv_color_hex(0x001C40), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel40, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel40, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel40, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel39 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_Panel39, 259);
    lv_obj_set_height(ui_Panel39, 236);
    lv_obj_set_x(ui_Panel39, -188);
    lv_obj_set_y(ui_Panel39, 54);
    lv_obj_set_align(ui_Panel39, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel39, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel39, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel39, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -186);
    lv_obj_set_y(ui_Label18, -104);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Object Detected");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button13 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Button13, 274);
    lv_obj_set_height(ui_Button13, 102);
    lv_obj_set_x(ui_Button13, 206);
    lv_obj_set_y(ui_Button13, 159);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0x0457FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button13, lv_color_hex(0x000D5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button13, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image23 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image23, &ui_img_102514673);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image23, 210);
    lv_obj_set_y(ui_Image23, 157);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image23, 200);

    ui_Panel41 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_Panel41, 267);
    lv_obj_set_height(ui_Panel41, 257);
    lv_obj_set_x(ui_Panel41, 205);
    lv_obj_set_y(ui_Panel41, -66);
    lv_obj_set_align(ui_Panel41, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel41, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel41, lv_color_hex(0x004FB6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel41, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel41, lv_color_hex(0x001C40), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel41, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel41, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel41, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image21 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image21, &ui_img_camara_png);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image21, 205);
    lv_obj_set_y(ui_Image21, -65);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imagesquare = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_imagesquare, &ui_img_square_png);
    lv_obj_set_width(ui_imagesquare, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imagesquare, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imagesquare, -188);
    lv_obj_set_y(ui_imagesquare, 54);
    lv_obj_set_align(ui_imagesquare, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imagesquare, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imagesquare, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imagesquare, 800);

    ui_imagetrangle = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_imagetrangle, &ui_img_triangle_png);
    lv_obj_set_width(ui_imagetrangle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imagetrangle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imagetrangle, -187);
    lv_obj_set_y(ui_imagetrangle, 56);
    lv_obj_set_align(ui_imagetrangle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imagetrangle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imagetrangle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imagetrangle, 1000);

    ui_imagecircle = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_imagecircle, &ui_img_circle_png);
    lv_obj_set_width(ui_imagecircle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imagecircle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imagecircle, -188);
    lv_obj_set_y(ui_imagecircle, 56);
    lv_obj_set_align(ui_imagecircle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imagecircle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imagecircle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_imagecircle, 900);

    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);

}
